DROP DATABASE IF EXISTS "HoneyRaes";

CREATE DATABASE "HoneyRaes";

\c HoneyRaes

CREATE TABLE Customer (
    Id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL,
    Address TEXT NOT NULL
);

CREATE TABLE Employee (
    Id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Name TEXT NOT NULL,
    Specialty TEXT NOT NULL
);

CREATE TABLE ServiceTicket (
    Id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CustomerId INTEGER NOT NULL REFERENCES Customer (Id),
    EmployeeId INTEGER REFERENCES Employee (Id),
    Description TEXT NOT NULL, 
    Emergency BOOLEAN NOT NULL DEFAULT FALSE,
    DateCompleted TIMESTAMP  
);

